### ISSUE TITLE
Unable to save redirect item

### ISSUE THREAD

**Issue by MilanLund** [michael419/xperience-community-redirects#2]
XbyK version is `29.5.2`.
I am encountering an issue that prevents a redirect item from being saved. I followed the installation steps as outlined in the README.md file. However, when I attempted to create the first redirect item, the following error occurred:

![iScreen Shoter - Google Chrome - 241004084429](https://github.com/user-attachments/assets/528bf80b-3b53-4646-a903-a9902f0a1c35)

![image](https://github.com/user-attachments/assets/c834f2b7-7101-4462-b87e-a0c6f59c4573)

**Comment by michael419** [comment]
Thanks for submitting this @MilanLund

Verified in my local dev environment. 

Will issue a fix and new release in the next couple of days.

**Comment by michael419** [comment]
Resolved in v1.0.1.
