### ISSUE TITLE
Event Log Errors When Creating and Deleting Redirect Items with Continuous Integration Enabled

### ISSUE THREAD

**Issue by MilanLund** [michael419/xperience-community-redirects#3]
Xperience by Kentico version: `29.6.1`
Package version: `1.0.1`

I have tested version `1.0.1` of this package and can confirm that the [original issue](https://github.com/michael419/xperience-community-redirects/issues/2) has been resolved. However, I am now encountering errors in the Event Log when creating and deleting redirect items on projects where Continuous Integration is enabled. I have tested this on two projects: one empty project and one client project, and the issue persists on both.

![red-eventlog](https://github.com/user-attachments/assets/78b30808-4cdb-4e00-b9b7-debeedde84e1)
![image](https://github.com/user-attachments/assets/de78b940-8712-4561-a4c4-70a83573e4dd)

The issue also occurs when serializing data in the `CDRepository`.

![image](https://github.com/user-attachments/assets/3504cdbe-c09e-496a-8b84-c1e5bf2491ad)

If you don't need to serialize redirect items, a workaround is to add `<ObjectType>xperiencecommunity.redirect</ObjectType>` inside the `<ExcludedObjectTypes>` section of the `repository.config` file for both `CIRepository` and `CDRepository`.

**Comment by michael419** [comment]
Thanks @MilanLund. I will get this resolved ASAP.

**Comment by michael419** [comment]
@MilanLund this is resolved.

I was able to replicate the issue on a brand new Dancing Goat project with CI and CD enabled and `v1.0.1` installed.

The issue is resolved after installing `v1.0.3`.
